### ISSUE TITLE
Additionals additional line at the end

### ISSUE THREAD

**Issue by hrnagesh-zz** [kvnallen/Dapper.DynamicReportGenerator#2]

**Comment by kvnallen** [comment]
👋!

Could you describe better your idea?

**Comment by hrnagesh-zz** [comment]
Hi Allen, 
Steps used
* Got collection from Dapper query
* used CsvGenerator.GetStringReport to output contents onto CSV file.

At the end of the line; i am seeing additional empty lines (\n)

![image](https://user-images.githubusercontent.com/11337231/54856853-e1675700-4cd2-11e9-8955-565002041b9b.png)

Here 48146, 7 rows were extra.

**Comment by kvnallen** [comment]
Hi @hrnagesh , a fix was published and it will be available at nuget for download after index and validation by microsoft.

![image](https://user-images.githubusercontent.com/3659874/54867099-2b941b00-4d5b-11e9-82ee-343fafd9fef9.png)

Please, update your package and let me know if you have a trouble.

**Comment by hrnagesh-zz** [comment]
Thanks Allen..
